stages:
  - test

playwright-test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.58.0-jammy
  
  script:
    - npm install
    - npx playwright install --with-deps
    - echo "Running Playwright tests..."
    - npx playwright test tests/validateVariables.spec.js --reporter=json,html
    - mv playwright-report/results.json failed-pages-results.json || mv playwright-report/failed-pages-results.json failed-pages-results.json || true

  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
      - failed-pages-results.json
    expire_in: 2 days
  after_script:
    - echo "Pipeline is working!"
    - ls -R playwright-report/ || echo "No folder found."
  
