stages:
  - test

playwright-test:
  stage: test
  
  script:
    - npm install
    - npx playwright install
    - npm validateVariables.spec.js

  artifacts:
    when: always
    paths:
      - playwright-report
      - failed-tests.json
    expire_in: 1 week
    - echo "Pipeline is working!"