stages:
  - test

playwright-test:
  stage: test
  
  script:
    - npm install
    - npx playwright install
    - npm validateVariables.spec.js

  artifacts:
    when: always
    paths:
      - failed-pages.html
    - echo "Pipeline is working!"